* $$ JOB JNM=LVTOC,USER='ME',CLASS=0,DISP=D
* $$ LST LST=00E,CLASS=A,DISP=D,JSEP=0
// JOB     LVTOC       - VOLUME VTOC DISPLAY UTILITY
// ASSGN   SYS004,X'131'
// ASSGN   SYS005,X'00E'
// EXEC    PGM=LVTOC
/*
/&
* $$ EOJ
