* $$ JOB JNM=APPLCICS,DISP=D,CLASS=0
* $$ LST LST=00E,FNO=A
// JOB APPLCICS CATALOG B.APPLCICS
// ASSGN SYSLST,X'00E'
// EXEC MAINT
 CATALS B.APPLCICS
 BKEND
 BSPCIC01 APPL AUTH=(ACQ,PASS)
 BSPCIC02 APPL AUTH=(ACQ,PASS) CICS CAN ACQUIRE & PASS TMLS
 BKEND
/*
/&
* $$ EOJ