* $$ JOB JNM=APPLPWR,DISP=D,CLASS=0
* $$ LST LST=00E,FNO=A
// JOB APPLPWR CATALOG B.APPLTSO
// ASSGN SYSLST,X'00E'
// EXEC MAINT
 CATALS B.APPLPWR
 BKEND
POWER APPL AUTH=(ACQ,PASS),BUFFACT=5
 BKEND
/*
/&
* $$ EOJ