* $$ JOB JNM=INSTALL,USER='COZZIE',CLASS=0,DISP=D
* $$ LST JSEP=0,CLASS=A,DISP=D
* $$ PUN CLASS=B
// JOB INSTALL
// ASSGN SYS003,X'130'
// DLBL IJSYSPC,'TSO.PVT.CIL',99/365
// EXTENT SYS003,SORT01
// EXEC CORGZ
  MERGE PRV,RES
  COPYC VTPX.ALL
/*
/&
* $$ EOJ