* $$ JOB JNM=ESERV,CLASS=0,USER='ESERV'
* $$ LST CLASS=A
// JOB ESERV
*  DLBL IJSYSSL,'DOSVS.OPTIONAL.DOSVS'
*  DLBL IJSYSSL,'DOSVS.OPTIONAL.POWER.BTAM.QTAM'
*  DLBL IJSYSSL,'DOSVS.OPTIONAL.VSAM'
*  DLBL IJSYSSL,'DOSVS.OPTIONAL.VTAM'
*  EXTENT SYSSLB,OPTLB1
*  ASSGN SYSSLB,DISK,VOL=OPTLB1,SHR
// EXEC ESERV
 DSPLY E.COMREG
/*
/&
* $$ EOJ
